'use client';
import {useState,useEffect,useRef,FormEvent} from 'react';
import {Users,FileText,Plus,Download,Search,Check,Shirt,Pencil,Trash2,X,ShieldCheck,ChevronDown,CheckCircle2} from 'lucide-react';
import {createDistintaPdf, type DistintaPlayer as Player} from '@/lib/distinta-pdf';
const blank={firstName:'',lastName:'',number:'',code:'',documentType:'',documentNumber:''};
async function api<T=Record<string,unknown>>(url:string, method='GET',body?:unknown){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error||'Operazione non riuscita. Riprova.');return data;}
export default function Home(){
 const [players,setPlayers]=useState<Player[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [tab,setTab]=useState('distinta'),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState('');
 const [team,setTeam]=useState(''),[teamDraft,setTeamDraft]=useState(''),[teamEdit,setTeamEdit]=useState(false);
 const [match,setMatch]=useState({opponent:'',date:'',time:'',venue:'',competition:'Superlega Calcio Ferrara',shirt:'',category:'Calcio a 7',home:true});
 const [form,setForm]=useState(blank),[edit,setEdit]=useState<string|null>(null),[formError,setFormError]=useState(''),[busy,setBusy]=useState(false),[pdfBusy,setPdfBusy]=useState(false);
 const [staff,setStaff]=useState(Array.from({length:7},()=>({name:'',code:''})));
 const dialog=useRef<HTMLDialogElement>(null);
 async function load(){setLoading(true);setError('');try{const [p,t]=await Promise.all([api<Player[]>('/api/players'),api<{name:string}>('/api/team')]);setPlayers(p);setTeam(t.name);setTeamDraft(t.name);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(''),4000);return()=>clearTimeout(t);}},[message]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'select_distinta_players',title:'Seleziona convocati',description:'Sostituisce la selezione dei convocati nella distinta corrente. Non genera il PDF.',inputSchema:{type:'object',properties:{playerIds:{type:'array',items:{type:'string'},uniqueItems:true}},required:['playerIds'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const ids=(input as {playerIds:unknown}).playerIds;if(!Array.isArray(ids)||ids.some(id=>typeof id!=='string'||!players.some(p=>p.id===id)))throw new Error('Giocatori non validi');setSelected([...new Set(ids)]);setTab('distinta');return{selected:ids.length};}}, {signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[players]);
 const sorted=[...players].sort((a,b)=>a.number-b.number||a.lastName.localeCompare(b.lastName));
 const visible=sorted.filter(p=>`${p.firstName} ${p.lastName} ${p.number} ${p.code}`.toLowerCase().includes(query.toLowerCase()));
 const chosen=sorted.filter(p=>selected.includes(p.id));
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
 function openForm(p?:Player){setEdit(p?.id||null);setForm(p?{firstName:p.firstName,lastName:p.lastName,number:p.number?String(p.number):'',code:p.code,documentType:p.documentType,documentNumber:p.documentNumber}:blank);setFormError('');dialog.current?.showModal();}
 async function savePlayer(e:FormEvent){e.preventDefault();setBusy(true);setFormError('');try{const p=await api<Player>('/api/players',edit?'PUT':'POST',{...form,number:Number(form.number),...(edit?{id:edit}:{})});setPlayers(s=>edit?s.map(v=>v.id===edit?p:v):[...s,p]);dialog.current?.close();setMessage(edit?'Giocatore aggiornato':'Giocatore aggiunto alla rosa');}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 async function remove(p:Player){if(!confirm(`Eliminare ${p.firstName} ${p.lastName} dalla rosa?`))return;setBusy(true);try{await api('/api/players','DELETE',{id:p.id});setPlayers(s=>s.filter(x=>x.id!==p.id));setSelected(s=>s.filter(x=>x!==p.id));setMessage('Giocatore eliminato');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function saveTeam(e:FormEvent){e.preventDefault();setBusy(true);try{const t=await api<{name:string}>('/api/team','PUT',{name:teamDraft});setTeam(t.name);setTeamEdit(false);setMessage('Squadra salvata');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const dateLabel=match.date?match.date.split('-').reverse().join('/'):'';
 async function download(){if(!chosen.length||!team.trim())return;setPdfBusy(true);setError('');try{const bytes=await createDistintaPdf({team,match,players:chosen,staff});const blob=new Blob([bytes as BlobPart],{type:'application/pdf'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`Distinta-${team.replace(/[^a-zA-Z0-9À-ÿ]/g,'-')}-${match.date||'gara'}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setMessage('PDF fronte e retro generato');}catch(e){setError((e as Error).message||'Non è stato possibile generare il PDF. Riprova.');}finally{setPdfBusy(false);}}
 return <div className="shell">
 <aside className="sidebar"><a className="brand" href="/" aria-label="Distinta 7, home"><span className="brand-icon">7</span><span>DISTINTA<span className="brand-seven">7</span></span></a><div className="sidebar-label">IL TUO CLUB</div><button className="club" onClick={()=>setTeamEdit(true)}><span className="club-icon"><Shirt size={21}/></span><span>{team||'La tua squadra'}<small>Calcio a 7</small></span><ChevronDown size={15}/></button><nav><button className={tab==='distinta'?'nav active':'nav'} onClick={()=>setTab('distinta')}><FileText size={19}/>Distinta di gara</button><button className={tab==='rosa'?'nav active':'nav'} onClick={()=>setTab('rosa')}><Users size={19}/>Rosa giocatori<span className="nav-count">{players.length}</span></button></nav><div className="sidebar-bottom"><ShieldCheck size={18}/><div>Il tuo spazio squadra<small>Anagrafica riservata</small></div></div></aside>
 <div className="main"><header className="topbar"><span>Gestione squadra <span className="breadcrumb">/ {tab==='distinta'?'Distinta di gara':'Rosa giocatori'}</span></span><span className="sport-tag">CALCIO A 7</span></header>
 <main className="workspace"><div className="page-heading"><div><p className="eyebrow">PRONTI PER IL FISCHIO D’INIZIO</p><h1>{tab==='distinta'?'La prossima partita.':'La tua rosa.'}</h1><p className="subtitle">{tab==='distinta'?'Scegli i convocati. La distinta è pronta in pochi clic.':'I dati dei tuoi giocatori, sempre pronti per la distinta.'}</p></div><button className="primary" onClick={()=>openForm()} disabled={loading}><Plus size={18}/>Aggiungi giocatore</button></div>
 {message&&<div role="status" className="toast"><CheckCircle2 size={18}/>{message}</div>}{error&&<div role="alert" className="error">{error} <button onClick={()=>void load()}>Riprova caricamento</button><button aria-label="Chiudi errore" onClick={()=>setError('')}><X size={16}/></button></div>}
 {(teamEdit||(!team&&!loading))&&<form className="team-form" onSubmit={saveTeam}><div><strong>Diamo un nome alla squadra</strong><p>Comparirà nell’intestazione di ogni distinta.</p></div><input required maxLength={80} aria-label="Nome squadra" value={teamDraft} onChange={e=>setTeamDraft(e.target.value)} placeholder="Nome della squadra"/><button className="primary" disabled={busy}>Salva squadra</button>{team&&<button type="button" className="icon-btn" aria-label="Annulla" onClick={()=>setTeamEdit(false)}><X size={18}/></button>}</form>}
 <div className={tab==='distinta'?'work-grid':'work-grid roster-only'}><section className="editor">
 {tab==='distinta'&&<section className="card match-card"><div className="section-heading"><div className="step">01</div><h2>La partita</h2><span className="muted small">Dati facoltativi</span></div><div className="match-form"><label className="wide">Squadra avversaria<input maxLength={80} value={match.opponent} placeholder="Contro chi giochiamo?" onChange={e=>setMatch({...match,opponent:e.target.value})}/></label><label>Data<input type="date" value={match.date} onChange={e=>setMatch({...match,date:e.target.value})}/></label><label>Ora<input type="time" value={match.time} onChange={e=>setMatch({...match,time:e.target.value})}/></label><label>Campo<input maxLength={100} value={match.venue} placeholder="Nome del campo" onChange={e=>setMatch({...match,venue:e.target.value})}/></label><label>Maglia / colore<input maxLength={40} value={match.shirt} onChange={e=>setMatch({...match,shirt:e.target.value})}/></label><label>Categoria<input maxLength={80} value={match.category} onChange={e=>setMatch({...match,category:e.target.value})}/></label><label>Giochiamo<select value={match.home?'casa':'trasferta'} onChange={e=>setMatch({...match,home:e.target.value==='casa'})}><option value="casa">In casa</option><option value="trasferta">In trasferta</option></select></label><label>Competizione<input maxLength={80} value={match.competition} placeholder="Campionato o torneo" onChange={e=>setMatch({...match,competition:e.target.value})}/></label></div></section>}
 {tab==='distinta'&&<section className="card match-card"><div className="section-heading"><h2>Staff sul retro</h2><span className="muted small">Dati facoltativi</span></div><div className="staff-form">{['Assistente di parte','1° dirigente','2° dirigente','3° dirigente','Allenatore','Medico sociale','Addetto all’arbitro'].map((role,i)=><div className="staff-row" key={role}><label>{role}<input maxLength={80} value={staff[i].name} placeholder="Cognome e nome" onChange={e=>setStaff(s=>s.map((v,j)=>j===i?{...v,name:e.target.value}:v))}/></label><label>Tessera / documento<input maxLength={80} value={staff[i].code} onChange={e=>setStaff(s=>s.map((v,j)=>j===i?{...v,code:e.target.value}:v))}/></label></div>)}</div></section>}
 <section className="card players-card"><div className="section-heading">{tab==='distinta'&&<div className="step">02</div>}<h2>{tab==='distinta'?'I convocati':'Anagrafica giocatori'}</h2><span className="pill">{tab==='distinta'?`${chosen.length} selezionati`:`${players.length} giocatori`}</span></div><div className="roster-toolbar"><div className="search"><Search size={17}/><input aria-label="Cerca giocatore" placeholder="Cerca nome, numero o tessera" value={query} onChange={e=>setQuery(e.target.value)}/></div>{tab==='distinta'&&players.length>0&&<button className="text-btn" onClick={()=>setSelected(selected.length===players.length?[]:players.map(p=>p.id))}>{selected.length===players.length?'Deseleziona tutti':'Seleziona tutti'}</button>}</div>
 {loading?<div className="empty"><div className="spinner"/>Caricamento della rosa...</div>:players.length===0?<div className="empty"><span className="empty-icon"><Shirt size={30}/></span><h3>La stagione comincia dalla rosa</h3><p>Aggiungi il primo giocatore. Salveremo i suoi dati<br className="desktop-break"/> per tutte le prossime partite.</p><button className="secondary" onClick={()=>openForm()}><Plus size={17}/>Aggiungi il primo giocatore</button></div>:visible.length===0?<div className="empty"><h3>Nessun giocatore trovato</h3><p>Prova con un altro nome o numero.</p></div>:<div className="player-list"><div className="list-head"><span>GIOCATORE</span><span>TESSERAMENTO</span></div>{visible.map(p=><div className={`player-row ${selected.includes(p.id)&&tab==='distinta'?'selected':''}`} key={p.id}>{tab==='distinta'&&<input type="checkbox" aria-label={`Convoca ${p.firstName} ${p.lastName}`} checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/>}<span className="jersey">{p.number||'—'}</span><button className="player-name" onClick={()=>tab==='distinta'?toggle(p.id):openForm(p)}><strong>{p.lastName} {p.firstName}</strong><small>{p.number?`Maglia n. ${p.number}`:'Maglia da assegnare'}</small></button><span className="code">{p.code}</span><button className="icon-btn" aria-label={`Modifica ${p.firstName} ${p.lastName}`} onClick={()=>openForm(p)}><Pencil size={16}/></button>{tab==='rosa'&&<button className="icon-btn danger" disabled={busy} aria-label={`Elimina ${p.firstName} ${p.lastName}`} onClick={()=>void remove(p)}><Trash2 size={16}/></button>}</div>)}</div>}
 <div className="card-footer"><ShieldCheck size={15}/><span>I dati della rosa vengono salvati per le prossime partite.</span></div></section></section>
 {tab==='distinta'&&<aside className="preview-col"><div className="preview-heading"><span>ANTEPRIMA DISTINTA</span><span className="paper-tag">A4 · PDF</span></div><div className="paper"><div className="paper-brand"><span>D7</span><span>CALCIO A 7</span></div><h2>Distinta di gara</h2><p className="paper-team">{team||'La tua squadra'}</p><div className="paper-match"><div><span>AVVERSARIO</span><strong>{match.opponent||'Da definire'}</strong></div><div><span>DATA E ORA</span><strong>{dateLabel?`${dateLabel} ${match.time}`:'Da definire'}</strong></div><div><span>CAMPO</span><strong>{match.venue||'Da definire'}</strong></div>{match.competition&&<div><span>COMPETIZIONE</span><strong>{match.competition}</strong></div>}</div><div className="paper-table"><div className="paper-tr head"><span>N.</span><span>COGNOME E NOME</span><span>TESSERA</span></div>{chosen.map(p=><div className="paper-tr" key={p.id}><strong>{p.number||'—'}</strong><span>{p.lastName} {p.firstName}</span><span>{p.code}</span></div>)}{!chosen.length&&<div className="paper-empty"><Users size={24}/><p>I convocati appariranno qui</p><small>Seleziona i giocatori dalla rosa</small></div>}</div><div className="paper-sponsors">{['rush','europa','su','trento-trieste'].map((name,i)=><img key={name} src={`/distinta/${name}.jpg`} alt={['Rush Music Lab','Europa KBLA Eventos','SU','Palazzo Trento Trieste'][i]}/>)}</div><div className="paper-signature"><span>Firma del responsabile</span><div/></div><div className="paper-bottom"><span>{chosen.length} giocatori convocati</span><span>Distinta 7</span></div></div><div className="download-card"><div><strong>La tua distinta, pronta da portare.</strong><p>Scarica il PDF e stampalo o invialo.</p></div><button className="download" disabled={!chosen.length||!team||pdfBusy} onClick={()=>void download()}><Download size={19}/>{pdfBusy?'Generazione PDF...':'Scarica distinta PDF'}</button>{!team?<small>Salva il nome della squadra per continuare.</small>:!chosen.length?<small>Seleziona almeno un giocatore per scaricare.</small>:<small><Check size={14}/> {chosen.length} convocati nella distinta</small>}</div><p className="model-note">Modello fornito · Fronte e retro A4 · Sponsor in fondo al retro</p></aside>}
 </div><footer className="footer"><span>DISTINTA 7</span><span>Meno scartoffie. Più calcio.</span></footer></main></div>
 <dialog ref={dialog} className="player-dialog" onCancel={()=>{if(busy)return;}}><form onSubmit={savePlayer}><div className="dialog-heading"><div><p className="eyebrow">ANAGRAFICA SQUADRA</p><h2>{edit?'Modifica giocatore':'Nuovo giocatore'}</h2></div><button type="button" className="icon-btn" aria-label="Chiudi" onClick={()=>dialog.current?.close()}><X size={22}/></button></div><p className="subtitle">Inserisci i dati come riportati sul tesseramento.</p><div className="dialog-fields"><label>Nome<input autoFocus required maxLength={80} value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} placeholder="Nome"/></label><label>Cognome<input required maxLength={80} value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} placeholder="Cognome"/></label><label>Numero di maglia<input type="number" min="1" max="99" value={form.number} onChange={e=>setForm({...form,number:e.target.value})} placeholder="Da assegnare (1–99)"/></label><label>Tipo documento<input maxLength={80} value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})} placeholder="Carta d’identità"/></label><label>Numero documento<input maxLength={80} value={form.documentNumber} onChange={e=>setForm({...form,documentNumber:e.target.value})}/></label><label>Codice tesseramento<input required maxLength={80} value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="Es. 00123456"/></label></div>{formError&&<p role="alert" className="form-error">{formError}</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={()=>dialog.current?.close()}>Annulla</button><button className="primary" disabled={busy}>{busy?'Salvataggio...':edit?'Salva modifiche':'Salva giocatore'}</button></div></form></dialog>
 </div>;
}
